### ISSUE TITLE
7 write media queries to make the page responsive

### ISSUE THREAD

**Issue by vortex6688** [usb777/AdviceNyc#12]
Write media queries to make the page responsive...

Breakpoint:
- 1200px
- 960px
- 640px (768px)

// TODO Discuss the breakpoints to make final decision

- [x]  Style responsive menu https://github.com/usb777/AdviceNyc/issues/13

- [x] Implement responsive grid for the content section https://github.com/usb777/AdviceNyc/issues/16

- [x] Update footer markup and styles https://github.com/usb777/AdviceNyc/issues/19

**Comment by vortex6688** [comment]
I've finished the minimal grid setup for 360px and up, page looks readable and elements do not overlap each other, any future fixes regarding the  responsiveness should be addressed in a newly created issues.
